name: Build APK

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WaspWingTempCtrl

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: 设置 Android SDK
        uses: android-actions/setup-android@v3

      - name: 授权 gradlew
        run: chmod +x gradlew

      - name: 编译 Release APK
        run: ./gradlew assembleRelease

      - name: 上传 APK 构建产物
        uses: actions/upload-artifact@v4
        with:
          name: WaspWingTempCtrl-APK
          path: WaspWingTempCtrl/app/build/outputs/apk/release/*.apk
